version: 2.1
defaults: &defaults
  docker:
    - image: nixos/nix
commands:
  setup:
    description: "setup environment"
    steps:
      - run:
          name: "nix"
          command: |
            nix-channel --add https://nixos.org/channels/nixos-18.09
            nix-channel --update
      - run:
          name: "install"
          command: |
            nix-env -f "<nixpkgs>" -iA cachix -f https://cachix.org/api/v1/install
            nix-env -f "<nixpkgs>" -i openssh
            nix-env -f "<nixpkgs>" -i git
      - run:
          name: "cachix"
          command: |
            cachix use free-algebras
      - checkout
  cachix-push:
    description: "cachix push"
    parameters:
      o:
        type: string
        default: "./result"
    steps:
      - run:
          name: "cachix push"
          command: cachix push free-algebras << parameters.o >>
jobs:
  GHC881:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 881"
          command: |
            nix-build -A free-category -o result-fc --argstr compiler ghc881
            nix-build -A examples -o result-ex --argstr compiler ghc881
      - cachix-push:
          o: result-fc
      - cachix-push:
          o: result-ex
  GHC865:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 865"
          command: |
            nix-build -A free-category -o result-fc --arg benchmarks true --argstr compiler ghc865
            nix-build -A examples -o result-ex --argstr compiler ghc865
      - cachix-push:
          o: result-fc
      - cachix-push:
          o: result-ex
  GHC844:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 844"
          command: |
            nix-build -A free-category -o result-fc --arg benchmarks true --argstr compiler ghc844
            nix-build -A examples -o result-ex --argstr compiler ghc844
      - cachix-push:
          o: result-fc
      - cachix-push:
          o: result-ex
  GHC822:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 822"
          command: |
            nix-build -A free-category -o result-fc --arg benchmarks true --argstr compiler ghc822
            nix-build -A examples -o result-ex --argstr compiler ghc822
      - cachix-push:
          o: result-fc
      - cachix-push:
          o: result-ex
          
  GHC802:
    <<: *defaults
    steps:
      - setup
      - run:
          name: "GHC 802"
          command: |
            nix-build -A free-category -o result-fc --arg benchmarks true --argstr compiler ghc802
            nix-build -A examples -o result-ex --argstr compiler ghc802
      - cachix-push:
          o: result-fc
      - cachix-push:
          o: result-ex

workflows:
  build:
    jobs:
      - GHC881
      - GHC865
      - GHC844
      - GHC822
      - GHC802

